birthdaycountdown/urls.py
from django.urls import path
# from django.conf import settings
# from django.conf.urls.static import static
# from django.contrib.auth import views as auth_views
from django.conf.urls import include


from . import views

app_name = 'birthdaycountdown'

urlpatterns = [
    path("", views.index, name="index")
]

cwalterbuilds/urls.py
from django.contrib import admin
from django.urls import path, include


# from django.conf.urls.static import static
# from django.conf import settings




# These are used for custom error pages...

handler404 = 'myprojects.views.error_404'
handler500 = 'myprojects.views.error_500'
handler403 = 'myprojects.views.error_403'
handler400 = 'myprojects.views.error_400'


urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include("myprojects.urls")),
    path("polls/", include("polls.urls")),
    path("ordersorter/", include('ordersorter.urls')),
    path("birthdaycountdown/", include('birthdaycountdown.urls')),
    # path("birthdaycountdown/", include('birthdaycountdown.urls'))
]

# if settings.DEBUG:
#    urlpatterns += static(settings.STATIC_URL,document_root = settings.STATIC_ROOT)
#    urlpatterns += static(settings.MEDIA_URL,document_root = settings.MEDIA_ROOT)


# this is added so that I do not have to call python3 manage.py collectstatic with every change to css files.
# if settings.DEBUG:
#     urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)


#Add Django site authentication urls (for login, logout, password management)

urlpatterns += [
    path('accounts/', include('django.contrib.auth.urls')),
]

myprojects/urls.py
from django.urls import path
# from django.conf import settings
# from django.conf.urls.static import static
# from django.contrib.auth import views as auth_views
from django.conf.urls import include


from . import views

app_name = 'myprojects'

urlpatterns = [
    path("", views.index, name="index"),
    path("myprojects", views.myprojects, name="myprojects"),
    path("login/", views.login_view, name="login"),
    path("logout", views.logout_view, name="logout"),
    path("register", views.register, name="register"),
    
    # path('accounts/', include('django.contrib.auth.urls')),
    
]

ordersorter/urls.py
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static

from . import views

app_name = 'ordersorter'

urlpatterns = [
    # ex: /ordersorter/
    path("", views.index, name="index"),
    path("create", views.create, name="create"),
    path("edit/<int:question_id>", views.edit, name="edit"),
    path('<int:question_id>/poll', views.poll, name='poll'),
    path('<int:question_id>/results', views.results, name='results'),


]

    

polls/urls.py
from django.urls import path

from . import views

app_name = 'polls'

# urlpatterns = [
#     # ex: /polls/
#     path('', views.index, name='index'),
#     # ex: /polls/5/
#     path('<int:question_id>/', views.detail, name='detail'),
#     # ex: /polls/5/results/
#     path('<int:question_id>/results/', views.results, name='results'),
#     # ex: /polls/5/vote/
#     path('<int:question_id>/vote/', views.vote, name='vote'),
# ]

urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('<int:pk>/', views.DetailView.as_view(), name='detail'),
    path('<int:pk>/results/', views.ResultsView.as_view(), name='results'),
    path('<int:question_id>/vote/', views.vote, name='vote'),
]

myprojects/models.py
from django.db import models
# from django.contrib.auth.models import AbstractUser


# Create your models here.

# class User(AbstractUser):
#     pass

myprojects/views.py
from django.shortcuts import render
# from ordersorter.models import User
from django.contrib.auth.models import User

from django.contrib.auth import authenticate, login, logout
from django.db import IntegrityError
from django.http import HttpResponse, HttpResponseRedirect

from django.urls import reverse
# from django.contrib.auth.decorators import login_required, user_passes_test

# from .models import User, Listing, Bid, Comment
# from .forms import CommentForm, ListingForm, BidForm

# Create your views here.
def index(request):
    
    return render(request, "myprojects/index.html", {

    })

def myprojects(request):
    return render(request, "myprojects/myprojects.html", {

    })


# HTTP Error 404
def error_404(request, exception):
    data = {
        'errorNum': '404',
        'errorDirections': 'The page you are looking for was not found.',
    }
    return render(request,'ordersorter/error.html', data)

def error_500(request):
    data = {
        'errorNum': '500',
        'errorTitle': 'Opps! Internal Server Error!',
        'errorDirections': 'Unfortunately we\'re having trouble loading the page you are looking for. Please come back in a while.'
    }
        
    return render(request,'ordersorter/error.html', data)

def error_400(request, exception):
    data = {
        'errorNum': '400',
        'errorTitle': 'Opps! Bad Request',
        'errorDirections': 'The server cannot process the request due to something that is perceived to be a client error.'
    }
        
    return render(request,'ordersorter/error.html', data)

def error_403(request, exception):
    data = {
        'errorNum': '403',
        'errorTitle': 'Opps! Forbidden',
        'errorDirections': 'Unfortunately the page you are trying to reach is forbidden'
    }
        
    return render(request,'ordersorter/error.html', data)


# Login, Register, and Logout....

def login_view(request):
    if request.method == "POST":

        # Attempt to sign user in
        username = request.POST["username"]
        password = request.POST["password"]
        user = authenticate(request, username=username, password=password)

        # Check if authentication successful
        if user is not None:
            login(request, user)
            return HttpResponseRedirect(reverse("myprojects:index"))
        else:
            return render(request, "myprojects/registration/login.html", {
                "message": "Invalid username and/or password."
            })
    else:
        return render(request, "myprojects/registration/login.html")


def logout_view(request):
    logout(request)
    return HttpResponseRedirect(reverse("myprojects:index"))


def register(request):
    if request.method == "POST":
        username = request.POST["username"]
        email = request.POST["email"]

        # Ensure password matches confirmation
        password = request.POST["password"]
        confirmation = request.POST["confirmation"]
        if password != confirmation:
            return render(request, "myprojects/registration/register.html", {
                "message": "Passwords must match."
            })

        # Attempt to create new user
        try:
            user = User.objects.create_user(username, email, password)
            user.save()
        except IntegrityError:
            return render(request, "myprojects/registration/register.html", {
                "message": "Username already taken."
            })
        login(request, user)
        return HttpResponseRedirect(reverse("myprojects:index"))
    else:
        return render(request, "myprojects/registration/register.html")

myprojects/templates/myprojects/index.html
{% extends "myprojects/layout.html" %}

{% load static %}

{% block style %}
<!-- <link rel="stylesheet" type="text/css" href="{% static 'myprojects/styles.css' %}"> -->
<!-- <link href="{% static 'myprojects/styles.css' %}" rel="stylesheet"> -->

<style>
.bg-img {
  min-height: 100%;
  background-image: url("{% static  'myprojects/images/NightSky-mohammad-alizade.jpg'%}");
  /* background-image: url("{% static  'myprojects/images/SimplePlant-pawel-czerwinski.jpg'%}"); */
  background-repeat: no-repeat;
  /* // this is the key to make sure the picture is the full background */
  width: 100%;
  background-size: 100% 100%; 
  color: ghostwhite;
  resize: both;
  overflow: scroll;
  padding-top: 100px;
  padding-bottom: 100px;
  text-shadow: 2px 2px black;
  
  

  /* margin-top: 50px; */
}

</style>
{% endblock %}

{% block body %}

    <main class="px-3 text-center">
      <div class="bg-img">
        <h1>CWalterBuilds</h1>
        <p>I build things and teach others to build.</p>
        <p>
          <a href="{% url 'myprojects:myprojects' %}" class="btn btn-lg btn-info fw-bold border-dark bg-info">Learn more</a>
        </p>
        
      </div>
         
    </main>
    
{% endblock %}

myprojects/templates/myprojects/layout.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <meta name="description" content="">
        <meta name="author" content="Chris Walter">
        <meta name="generator" content="Hugo 0.87.0">

        <title>{% block title %}CWalterBuilds{% endblock %}</title>
            <!-- Bootstrap core CSS -->
            <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-KyZXEAg3QhqLMpG8r+8fhAXLRk2vvoC2f3B09zVXn8CA5QIVfZOJ3BCsw2P0p/We" crossorigin="anonymous">
            <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
        <style>
        .bd-placeholder-img {
            font-size: 1.125rem;
            text-anchor: middle;
            -webkit-user-select: none;
            -moz-user-select: none;
            user-select: none;
        }

        @media (min-width: 768px) {
            .bd-placeholder-img-lg {
            font-size: 3.5rem;
            }

          #login {
            padding: 0px 5px;
            /* margin: 10px; */
          }
        }

        body {
          padding: 10px
        }
        
        </style>
        

        {% block style %}

        {% endblock %}

        <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
        <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>

        <!-- Javascript stuff for birthdaycountdown -->
        <link rel="stylesheet" href="//code.jquery.com/ui/1.13.2/themes/base/jquery-ui.css">
        <!-- <link rel="stylesheet" href="/resources/demos/style.css"> -->
        <script src="https://code.jquery.com/jquery-3.6.0.js"></script>
        <script src="https://code.jquery.com/ui/1.13.2/jquery-ui.js"></script>

        {% block script %}
        {% endblock %}
      </head>

        <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
          <div>
            <img style="max-width: 3rem;" src="{% static 'myprojects/images/CWBuildsLogo.png'%}" alt="CWBuildsLogo">
            <a class="navbar-brand" href="/">CWalterBuilds</a>
          </div>
          
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav ms-auto">
              <li class="nav-item">
                <a class="nav-link" href="/">Home <span class="sr-only">(current)</span></a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="{% url 'myprojects:myprojects' %}">MyProjects</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="{% url 'ordersorter:index' %}">OrderSorter</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="{% url 'birthdaycountdown:index' %}">BirthdayCountdown</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="{% url 'polls:index' %}">Polls</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="#">Contact</a>
              </li>

              {% if user.is_authenticated %}
              <li id="login"><a href="{% url 'myprojects:logout' %}" class="btn btn-secondary">Logout</a></li>
              {% else %}
                <li id="login"><a href="{% url 'myprojects:register' %}" class="btn btn-light" role="button">SignUp</a></li>
                <li id="login"><a href="{% url 'myprojects:login' %}" class="btn btn-primary" role="button">Login</a></li>
              {% endif %}
            </ul>
          </div>
        </nav>

        <div>
          {% if user.is_authenticated %}
              Hello, <strong>{{ user.username }}</strong>.
              <a href="{% url 'password_change' %}">Change password</a>
          {% else %}
              Not signed in.
          {% endif %}
        </div>
          
          {% block body %}
          {% endblock %}
      
      </div>
    </body>
</html>

myprojects/templates/myprojects/testProjects.html
<h2>Published Apps</h2>

<table class="table table-bordered">
    <thead>
      <tr>
        <th scope="col">
            <h5 class="card-table">
                <a href="https://cwalter50.github.io/apps/MemoriesTree.html"target="_blank" rel="noopener noreferrer" >MemoriesTree</a>
            </h5>
        </th>
        <th scope="col">
            <h5 class="card-table">
                <a href="https://cwalter50.github.io/apps/OutOfTime.html"target="_blank" rel="noopener noreferrer" >OutOfTime!</a>
            </h5>
        </th>
        <th scope="col">
            <h5 class="card-table">
                <a href="https://cwalter50.github.io/apps/Slidearoo.html"target="_blank" rel="noopener noreferrer" >Slidearoo</a>
            </h5>
        </th>
        <th scope="col">Handle</th>
      </tr>
    </thead>
    <tbody>
      <tr>
        <th scope="row">1</th>
        <td>Mark</td>
        <td>Otto</td>
        <td>@mdo</td>
      </tr>
      <tr>
        <th scope="row">2</th>
        <td>Jacob</td>
        <td>Thornton</td>
        <td>@fat</td>
      </tr>
      <tr>
        <th scope="row">3</th>
        <td colspan="2">Larry the Bird</td>
        <td>@twitter</td>
      </tr>
    </tbody>
  </table>

<ul class="list-group">
    <div class="card-columns">
        <div class="card" style="width: 18rem;">
            <img class="card-img-top" src="{% static 'myprojects/images/MemoriesTreeLogo.png' %}" alt="Card image cap">
            <div class="card-body">
                <h5 class="card-title"><a href="https://cwalter50.github.io/apps/MemoriesTree.html"target="_blank" rel="noopener noreferrer" >MemoriesTree</a></h5>
                <p class="card-text">iOS Journaling App. Perfect for journaling and sharing your memories or keeping them private. First Firebase App.</p>
                <a href="https://apps.apple.com/us/app/memoriestree/id1263250242?ls=1" target="_blank" rel="noopener noreferrer" class="btn btn-primary">Download MemoriesTree</a>
            </div>
        </div>
        <div class="card" style="width: 18rem;">
            <img class="card-img-top" src="{% static 'myprojects/images/OutOfTimeLogo.png' %}" alt="Card image cap">
            <div class="card-body">
                <h5 class="card-title"><a href="https://cwalter50.github.io/apps/OutOfTime.html" target="_blank" rel="noopener noreferrer">OutOfTime!</a></h5>
                <p class="card-text">iOS and tvOS Family fun word game. Take turns listing items in a certain category before the music stops. Play music from your device in the game, In-App Purchases, and more.</p>
                <a href="https://apps.apple.com/us/app/outoftime/id1333852115" target="_blank" rel="noopener noreferrer" class="btn btn-primary">Download OutOfTime!</a>
            </div>
        </div>
        <div class="card" style="width: 18rem;">
            <img class="card-img-top" src="{% static 'myprojects/images/SlidearooLogo.png' %}" alt="Card image cap">
            <div class="card-body">
                <h5 class="card-title"><a href="https://cwalter50.github.io/apps/Slidearoo.html" target="_blank" rel="noopener noreferrer">Slidearoo</a></h5>
                <p class="card-text">iOS and tvOS App. Play game of Fifteen slide puzzles with numbers or pictures. You can even play with your own photos. Keep your stats and compete with others. Cloudkit, In-App Purchase, Swift.</p>
                <a href="https://apps.apple.com/us/app/slidearoo/id1395435780" target="_blank" rel="noopener noreferrer" class="btn btn-primary">Download Slidearoo</a>
            </div>
        </div>
    </div>
</ul>