cwalterbuilds/urls.py
from django.contrib import admin
from django.urls import path, include


# from django.conf.urls.static import static
# from django.conf import settings




# These are used for custom error pages...

handler404 = 'myprojects.views.error_404'
handler500 = 'myprojects.views.error_500'
handler403 = 'myprojects.views.error_403'
handler400 = 'myprojects.views.error_400'


urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include("myprojects.urls")),
    path("polls/", include("polls.urls")),
    path("ordersorter/", include('ordersorter.urls')),
    path("birthdaycountdown/", include('birthdaycountdown.urls')),
    # path("birthdaycountdown/", include('birthdaycountdown.urls'))
]

# if settings.DEBUG:
#    urlpatterns += static(settings.STATIC_URL,document_root = settings.STATIC_ROOT)
#    urlpatterns += static(settings.MEDIA_URL,document_root = settings.MEDIA_ROOT)


# this is added so that I do not have to call python3 manage.py collectstatic with every change to css files.
# if settings.DEBUG:
#     urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)


#Add Django site authentication urls (for login, logout, password management)

urlpatterns += [
    path('accounts/', include('django.contrib.auth.urls')),
]

ordersorter/urls.py
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static

from . import views

app_name = 'ordersorter'

urlpatterns = [
    # ex: /ordersorter/
    path("", views.index, name="index"),
    path("create", views.create, name="create"),
    path("edit/<int:question_id>", views.edit, name="edit"),
    path('<int:question_id>/poll', views.poll, name='poll'),
    path('<int:question_id>/results', views.results, name='results'),


]

    

polls/urls.py
from django.urls import path

from . import views

app_name = 'polls'

# urlpatterns = [
#     # ex: /polls/
#     path('', views.index, name='index'),
#     # ex: /polls/5/
#     path('<int:question_id>/', views.detail, name='detail'),
#     # ex: /polls/5/results/
#     path('<int:question_id>/results/', views.results, name='results'),
#     # ex: /polls/5/vote/
#     path('<int:question_id>/vote/', views.vote, name='vote'),
# ]

urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('<int:pk>/', views.DetailView.as_view(), name='detail'),
    path('<int:pk>/results/', views.ResultsView.as_view(), name='results'),
    path('<int:question_id>/vote/', views.vote, name='vote'),
]

polls/models.py
from django.db import models
import datetime
from django.utils import timezone
from django.contrib import admin

# Create your models here.

class Question(models.Model):
    question_text = models.CharField(max_length=200)
    pub_date = models.DateTimeField('date published')

    def __str__(self):
        return self.question_text
    
    @admin.display(
        boolean=True,
        ordering='pub_date',
        description='Published recently?',
    )


    def was_published_recently(self):
        now = timezone.now()
        return now - datetime.timedelta(days=1) <= self.pub_date <= now
    

class Choice(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    choice_text = models.CharField(max_length=200)
    votes = models.IntegerField(default=0)

    def __str__(self):
        return self.choice_text

ordersorter/forms.py
from django import forms
from .models import Question, Option


class QuestionForm(forms.ModelForm):
    class Meta:
        model = Question
        fields = ('question', 'description')
        labels = {
            'question': 'Question',
            'description': 'Description'
        }
        widgets = {
                   'question': forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Create Question'}),
                   'description': forms.Textarea(attrs={'class': 'form-control', 'placeholder': 'Question Description', 'rows':'3'}),
                } 


class OptionForm(forms.ModelForm):
  class Meta:
    model = Option
    fields = ["optionText"]
    labels = {
      'optionText':''
    }
    widgets = {
      'optionText': forms.TextInput(attrs={'class':'form-control', 'placeholder':'Add Option'})
    }

ordersorter/views.py
from django.shortcuts import render, get_object_or_404
from .forms import QuestionForm, OptionForm
from .models import Question, Option, Result
from django.http import HttpResponseRedirect
from django.urls import reverse
from django.http import HttpResponse, HttpResponseRedirect
from django.core import serializers

# Create your views here.

def index(request):
    questions = Question.objects.all
    user_questions = []
    if request.user.is_authenticated:
        user_questions = Question.objects.filter(user=request.user)
        # print(user_questions)
    return render(request, "ordersorter/index.html", {
        "questions": questions,
        "user_questions": user_questions
    })

def test(request):
    
    return render(request, "ordersorter/test.html")

def poll(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    print(request.method)
    # question = Question.objects.get(pk=question_id)
    if request.method == "POST":
        # the post name is in the name tag in the html... its not the id
        newname = request.POST["resultName"]
        items = request.POST.getlist("order")
        # items = request.POST.
        print(items)
        # items = request.POST['orderItem']
        theorder = {'items': items}
        newResult = Result(name=newname, order=theorder, question=question)

        newResult.save()
        # question.results.add(newResult)
        question.save()
        context = {
            'question': question,
        }
        return HttpResponseRedirect(reverse('ordersorter:results', args=(question.id,)))
        
        # return render(request, 'ordersorter/results.html', context)
    else:
        return render(request, 'ordersorter/poll.html', {
            'question': question,
        })


    

def edit(request, question_id):
    question = Question.objects.get(pk=question_id)
    # question = get_object_or_404(Question, pk=question_id)
    if request.method == "POST":
        if request.POST.get("button") == "add-option":
            newOptionText = request.POST["optionText"]
            if newOptionText != "":
                newOption = Option(optionText=newOptionText, question=question)
                newOption.save()
                questionText = request.POST["question"]
                description = request.POST["description"]
                question.question = questionText
                question.description = description
                question.save()
                # Always return an HttpResponseRedirect after successfully dealing
                # with POST data. This prevents data from being posted twice if a
                # user hits the Back button.
                return HttpResponseRedirect(reverse('ordersorter:edit', args=(question.id,)))
            else:
                context = {
                    'question': question,
                    'message': f"Option value cannot be empty",
                    'form': OptionForm()
                }
                return render(request, 'ordersorter/edit.html', context)
        if request.POST.get("button") == "update-question":
            questionText = request.POST["question"]
            description = request.POST["description"]
            question.save()
            return HttpResponseRedirect(reverse('ordersorter:edit', args=(question.id,)))

        print(request.POST)
        # delete the option, by first looping through all the options to find which one was clicked on
        for option in question.options.all():
            if f'{option.id}' in request.POST:
                option.delete()
                return HttpResponseRedirect(reverse('ordersorter:edit', args=(question.id,)))

    context = {
        'question': question,
        'form': OptionForm()
    }
    return render(request, 'ordersorter/edit.html', context)
    

def create(request):

    if request.method == 'GET':
        context = {
            'form': QuestionForm(),
            'message': ''
        }

        return render(request, "ordersorter/create.html", context)

    if request.method == 'POST':
        form = QuestionForm(request.POST, request.FILES)

        if form.is_valid():
            question = form.save(commit=False)
            question.user = request.user
            question.save()
            context = {
                "question": question
            }
            return HttpResponseRedirect(reverse('ordersorter:edit', args=(question.id,)))

        return render(request, "ordersorter/create.html")

def results(request, question_id):
    question = question = get_object_or_404(Question, pk=question_id)
    
    # if a result gets deleted, we should be able to reload the page...
    if request.method == 'POST':
        # print(request.POST)
        # delete the option, by first looping through all the options to find which one was clicked on
        resultId = request.POST['delete']
        # print(resultId)
        for result in question.results.all():
            # print(f"comparing {result.id} to {resultId}")
            if str(result.id) == str(resultId):
                # print(f"deleting result {result.id}")
            # if f'{result.id}' in request.POST:
                result.delete()
                return HttpResponseRedirect(reverse('ordersorter:results', args=(question.id,)))

    scoresDict = calculateScores(question)
    # sort the scores
    scoresDict = dict(sorted(scoresDict.items(), key=lambda item: item[1], reverse=True))
    # surveyStats contains an array of the winning message with the winner(s) and score along with loser, most ones, most topThress. 
    surveyStats = getSurveyStats(scoresDict, question)
    
    context = {
        'question': question,
        # 'results': results,
        'range':range(len(question.options.all())),
        'scoresDict': scoresDict,
        'surveyStats': surveyStats

    }
    return render(request, 'ordersorter/results.html', context)

# helper functions to calculate the results
def calculateScores(question):
    results = question.results.all()
    # empty dictionary, planning on storing the scores for each option
    scoresDict = {}
    for option in question.options.all():
        scoresDict[option.optionText] = 0
    # loop through the results order and add to the score for that option
    for result in results:
        mult = len(question.options.all())
        for item in result.order["items"]:
            # Add item to dictionary in case it was deleted from the list
            if item not in scoresDict:
                scoresDict[item] = 0
            scoresDict[item] += mult
            mult-=1
    return scoresDict

def getSurveyStats(scoresDict, question):
    results = []
    results.append(getWinnerOrLoser(scoresDict, "HIGHEST SCORE: ", True))
    results.append(getMostExtremes(question, "TOP CHOICE THE MOST: ", True))
    results.append(getMostTopOrBottomThree(question, "CHOSEN TOP 3 THE MOST: ", True))
    results.append(getWinnerOrLoser(scoresDict, "LOWEST SCORE: ", False))
    results.append(getMostExtremes(question, "LAST CHOICE THE MOST: ", False))
    results.append(getMostTopOrBottomThree(question, "CHOSEN IN BOTTOM 3 THE MOST: ", False))
    results.append(f"TOTAL SURVEYS: {len(question.results.all())}")
    return results
    
# this method will return either the highest or lowest score, based on the parameters. isWinner is used to determine max or min
def getWinnerOrLoser(scoresDict, output, isWinner):
    winners = []
    # first find highest score...
    if len(scoresDict.items()) == 0:
        return f"{output} None"
    highestScore = max(scoresDict.values()) if isWinner else min(scoresDict.values())
    
    # next find keys that match the highest score...
    for key, value in scoresDict.items():
        if value == highestScore:
            winners.append(key)
    # print(winners)
    message=f"{output}"
    if len(winners) == 1:
        message+=f"{winners[0]} ({highestScore})"
    elif len(winners) == 2:
        message+=f"{winners[0]} and {winners[1]} ({highestScore})"
    else:
        for i in range(0, len(winners)-1):
            message += f"{winners[i]}, "
        message += f"and {winners[-1]} "

        message += f"({highestScore})"
    return message

# this method can be used to determine which option has the most top choice and which one has the most bottom choice
def getMostExtremes(question, output, isTop):
    results = question.results.all()

    if len(results) == 0:
        return f"{output} None"
    # empty dictionary, planning on storing the scores for each option
    number1s = {}
    for result in results:
        if result.order["items"]:
            if len(result.order["items"]) > 0:
                pos = 0 if isTop else -1
                currentnum1 = result.order["items"][pos]
                if currentnum1 not in number1s:
                    number1s[currentnum1] = 1
                else:
                    number1s[currentnum1] += 1

    highestNum = max(number1s.values())
    # print(highestNum)
    mostOnes = []
    for key,value in number1s.items():
        if value == highestNum:
            mostOnes.append(key)
    # print(mostOnes)
    message=f"{output}"
    if len(mostOnes) == 1:
        message+=f"{mostOnes[0]} ({highestNum}) times"
    elif len(mostOnes) == 2:
        message+=f"{mostOnes[0]} and {mostOnes[1]} ({highestNum}) times"
    else:
        for i in range(0, len(mostOnes)-1):
            message += f"{mostOnes[i]}, "
        message += f"and {mostOnes[-1]} "
        message += f" ({highestNum}) times"
    return message

# this method will comput the options that are selected in the top 3 or bottom 3 the most.
def getMostTopOrBottomThree(question, output, isTop):
    results = question.results.all()
    # empty dictionary, planning on storing the scores for each option
    if len(results) == 0:
        return f"{output} None"
    top3s = {}
    for result in results:
        try:

polls/views.py
from django.shortcuts import get_object_or_404, render
from django.http import HttpResponse, HttpResponseRedirect
from .models import Question, Choice
from django.template import loader
from django.http import Http404
from django.urls import reverse
from django.views import generic

# Create your views here.

from .models import Choice, Question


class IndexView(generic.ListView):
    template_name = 'polls/index.html'
    context_object_name = 'latest_question_list'

    def get_queryset(self):
        """Return the last five published questions."""
        return Question.objects.order_by('-pub_date')[:5]


class DetailView(generic.DetailView):
    model = Question
    template_name = 'polls/detail.html'


class ResultsView(generic.DetailView):
    model = Question
    template_name = 'polls/results.html'


# def index(request):
#     latest_question_list = Question.objects.order_by('-pub_date')[:5]
#     context = {'latest_question_list': latest_question_list}
#     return render(request, 'polls/index.html', context)
#     # return HttpResponse("Hello, world. You're at the polls index.")


# def detail(request, question_id):
#     question = get_object_or_404(Question, pk=question_id)
#     return render(request, 'polls/detail.html', {
#         'question': question
#         })
#     # return HttpResponse("You're looking at question %s." % question_id)

# def results(request, question_id):
#     question = get_object_or_404(Question, pk=question_id)
#     return render(request, 'polls/results.html', {
#         'question': question
#         })

# def results(request, question_id):
#     response = "You're looking at the results of question %s."
#     return HttpResponse(response % question_id)

# def vote(request, question_id):
#     return HttpResponse("You're voting on question %s." % question_id)

def vote(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    try:
        selected_choice = question.choice_set.get(pk=request.POST['choice'])
    except (KeyError, Choice.DoesNotExist):
        # Redisplay the question voting form.
        return render(request, 'polls/detail.html', {
            'question': question,
            'error_message': "You didn't select a choice.",
        })
    else:
        selected_choice.votes += 1
        selected_choice.save()
        # Always return an HttpResponseRedirect after successfully dealing
        # with POST data. This prevents data from being posted twice if a
        # user hits the Back button.
        return HttpResponseRedirect(reverse('polls:results', args=(question.id,)))

ordersorter/templates/ordersorter/create.html
{% extends "myprojects/layout.html"%}

{% block body %}
<h1>Create a New Poll</h1>
<h3>{{ message }}</h3>
<form method="POST" enctype="multipart/form-data">
  {% csrf_token %}
  {{ form.as_p }}
  <div class="btn-right">
    <input class="btn btn-primary" type="submit" value="Create">
  </div>
</form>
  
{% endblock %}

ordersorter/templates/ordersorter/edit.html
{% extends "myprojects/layout.html" %}

{% block body %}
{% if message %}
    <div class="alert alert-warning" role="alert">
        {{ message }}
    </div>
{% endif %}

<h1>{{ question }}</h1>


<form class="mb-3" method="POST">
    {% csrf_token %}
    <div class="update-right">
        <button type="submit" id="update-button" class="btn btn-secondary" name="button" value="update-question">Update</button>
    </div>
    
    <div class="mb-3">
        <label for="question" class="form-label">Question</label>
        <input type="text" class="form-control" id="question" name="question" placeholder="Question" value="{{ question }}" required>
    </div>
    <div class="mb-3">
        <label for="questionDescription" class="form-label">Description</label>
        <textarea class="form-control" id="description" name="description" rows="3">{{ question.description }}</textarea>
    </div>
  
    <div class="row g-2">
        <div class="col-auto">
            <input type="text" class="form-control" name="optionText" id="optionText" placeholder="Add Option">
        </div>
        <div class="col-auto">
            <button type="submit" class="btn btn-primary mb-3" name="button" value="add-option">Add Option</button>
        </div>
    </div>
</form> 

<form class="mb-3" method="POST">
    {% csrf_token %}
    <ul class="list-group">
        {% for option in question.options.all %}
        <li class="list-group-item">
            <span class="option-name" name="option-name" id="option-name"> {{ option }}</span>
            <button type="submit" class="btn btn-close pull-right" aria-label="Close" name="{{ option.id }}" value="{{ option }}"></button>
        </li>
            
        {% endfor %}
    </ul>
</form>


{% endblock %}

ordersorter/templates/ordersorter/error.html
{% extends "myprojects/layout.html" %}

{% block body %}
<div class="page-wrap d-flex flex-row align-items-center">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12 text-center">
                <span class="display-1 d-block">{{ errorNum }}</span>
                <span class="display-5 d-block">{{ errorTitle }}</span>
                <div class="mb-4 lead">{{ errorDirections }}</div>
                <a href="/" class="btn btn-link">Back to Home</a>
            </div>
        </div>
    </div>
</div>

{% endblock %}

{% block style %}
<style>
    body {
    background: #dedede;
    }
    .page-wrap {
        min-height: 100vh;
    }
</style>
{% endblock %}

ordersorter/templates/ordersorter/index.html
{% extends "myprojects/layout.html" %}
{% load static %}

{% block body %}
<h1>OrderSorter</h1>
<div>
    <p>Create Survey Questions where responders can rank their answers. The results will be totaled, analyzed, and viewed.</p>
</div>
{% if user.is_authenticated %}
    <div>
        <h3>My Surveys</h3>
    </div>
    <div class="createSurveyButton">
        <a href="{% url 'ordersorter:create' %}" class="btn btn-primary">Create New Survey</a>
    </div>
    {% if user_questions %}
        <table class="table table-sm">
            <thead>
            <tr>
                <th scope="col">Question</th>
                <th scope="col" style="text-align: right;">Options</th>
            </tr>
            </thead>
            <tbody>
            {% for question in user_questions.all %}
                <tr>
                    <td>
                        <span>
                        {{ question }}
                        <div class="text-muted">
                            {{ question.description }}
                        </div>
                        </span>
                    </td>
                    <td style="text-align: right;">
                        {% if question.user == user %}
                            <a href="{% url 'ordersorter:edit' question.id %}" class="btn btn-secondary btn-sm">Edit</a>
                        {% endif %}
                        <a href="{% url 'ordersorter:poll' question.id %}" class="btn btn-primary btn-sm">Survey</a>
                        <a href="{% url 'ordersorter:results' question.id %}" class="btn btn-info btn-sm">Results</a>

                    </td>
                </tr>
            {% endfor %}
            </tbody>
        </table>
    {% else %}
        <p>No surveys are available.</p>
    {% endif %}
{% else %}
<div>
    <p>You must be signed in to create surveys</p>
</div>

{% endif %}

<div>
    <h3>Community Surveys</h3>
</div>
{% if questions %}
    <table class="table table-sm">
        <thead>
        <tr>
            <th scope="col">Question</th>
            <th scope="col" style="text-align: right;">Options</th>
        </tr>
        </thead>
        <tbody>
        {% for question in questions.all %}
            <tr>
                <td>
                    <span>
                    {{ question }}
                    <div class="text-muted">
                        {{ question.description }}
                    </div>
                    </span>
                </td>
                <td style="text-align: right;">
                    {% if question.user == user %}
                        <a href="{% url 'ordersorter:edit' question.id %}" class="btn btn-secondary btn-sm">Edit</a>
                    {% endif %}
                    <a href="{% url 'ordersorter:poll' question.id %}" class="btn btn-primary btn-sm">Survey</a>
                    <a href="{% url 'ordersorter:results' question.id %}" class="btn btn-info btn-sm">Results</a>   
                </td>
            </tr>
        {% endfor %}
        </tbody>
    </table>
{% else %}
    <p>No polls are available.</p>
{% endif %}




{% endblock %}

{% block style %}
<!-- <link rel="stylesheet" type="text/css" href="{% static 'myprojects/styles.css' %}"> -->
<link href="{% static 'ordersorter/styles.css' %}" rel="stylesheet">
{% endblock %}

ordersorter/templates/ordersorter/poll.html
{% extends "myprojects/layout.html" %}

{% load static %}

{% block body %}

<h2 class="display-4"> {{ question }}</h2>
<div class="description">{{ question.description }}</div>
<p></p>

    {% if question.options %}
        <form class="form-group" method="POST">
            {% csrf_token %}
            <div class="mb-3">
                <input type="text" class="form-control" id="resultName" name="resultName" placeholder="Name" required>
            </div>
            <div class="description">Order the items: top is the best, bottom is the worst</div>
            <div id="list">
            {% for option in question.options.all %}
                
                <div class="draggable" contenteditable="false" id="order" name="order">{{ option }}
                    <input type="hidden" id="hidden" name="order" value="{{ option }}">
                </div>
            {% endfor %}
            </div>
            <div class="center">
                <button id="submitPollButton" type="submit" class="btn btn-primary" value="addResult">Submit</button>
            </div>
            
        </form>

    {% else %}
        <h2>No Options added to Poll</h2>
    {% endif %}
    

<p></p>
<div id="test">Bye</div>

  
{% endblock %}

{% block script %}
    <script src="poll.js"></script>
    <script src="{% static 'ordersorter/poll.js' %}"></script>



{% endblock %}


{% block style %}
<link href="{% static 'ordersorter/styles.css' %}" rel="stylesheet">
{% endblock %}

ordersorter/templates/ordersorter/results.html
{% extends "myprojects/layout.html" %}

{% load static %}

{% block body %}
<h1>Survey results</h1>
          
    {% if question %}
        <h3>{{ question }}</h3>
        <p></p>
        <ul class="list-group">
            {% for stat in surveyStats %}
                <li class="list-group-item" id="result">{{ stat }}</li>
            {% endfor %}
          </ul>
        <div id="winner">{{ winnerMessage }}</div>
        <p></p>

        <table class="table table-dark" id="scoreTable">
            <thead><h3>Total Scores</h3></thead>
            <thead>
            <tr>
                {% for key, value in scoresDict.items %}
                    <th scope="col">{{ key }}</th>
                {% endfor %}
            </tr>
            </thead>
            <tbody>
                <tr>
                    {% for key, value in scoresDict.items %}
                    <td>{{ value }}</td>
                    {% endfor %}
                </tr>
            </tbody>
        </table>
        <p></p>
        <form method="POST">
            {% csrf_token %}
            <table class="table table-dark table-hover" id="responseTable" name="responseTable">
                <thead><h3>Survey Responses</h3></thead>
                <thead>
                <tr>
                    {% if question.user == user %}
                    <th scope="col">Delete</th>
                    {% endif %}
                    <th scope="col">#</th>
                    <th scope="col">Name</th>
                    {% for i in range %}
                        <th scope="col">{{ i }}</th>
                    {% endfor %}
                </tr>
                </thead>
                <tbody>
                    {% for result in question.results.all %}
                    <tr>
                        {% if question.user == user %}
                        <td><button type="button" class="openDeleteWarning btn btn-danger" data-toggle="modal" data-target="#exampleModal" data-id="{{ result.id }}" data-name="{{ result }}" aria-label="Close" name="{{ result.id }}" value="{{ result }}">Delete</button></td>
                        {% endif %}
                        <td>{{ forloop.counter }}</td>
                        <td>{{ result.name }}</td>
                        {% for item in result.order.items %}
                            <td>{{ item }}</td>
                        {% endfor %}

                    </tr>
                    {% endfor %}
                </tbody>
            </table>
        </form>
    {% else %}
        <div>No Question Found</div>
    {% endif %}

    <!-- Modal-Will appear when deletebutton is tapped -->
    <form method="POST">
        {% csrf_token %}
        <div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
            <div class="modal-dialog" role="document">
                <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="exampleModalLabel">Delete result?</h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <div class="modal-body">
                    <p>Are you sure you want to delete the result?</p>
                    <input type="text" name="resultId" id="resultId" value=""/>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-dismiss="modal">Cancel</button>
                    <button id="deleteButton" type="submit" class="btn btn-danger" name="delete" value="hello">Delete</button>
                </div>
                </div>
            </div>
        </div>
    </form>



{% endblock %}


{% block style %}
<link href="{% static 'ordersorter/styles.css' %}" rel="stylesheet">
{% endblock %}

{% block script %}
    <script src="{% static 'ordersorter/results.js' %}"></script>
    <script>
        // this is for the modal that appears when delete is tapped 
        $(document).on("click", ".openDeleteWarning", function () {
            var resultId = $(this).data('id');
            var name = $(this).data('name');
            
            var output = `Are you sure you want to delete the result: ${name}?`;
            $(".modal-body").html( output );
            // $(".modal-footer #deleteButton").name = resultId;
            // $(".modal-footer #deleteButton").vale = name;

            // I could not figure out how to change the name of the button, so I changed the value... 
            // I needed to change the code on the python side to make it work out.
            $('#deleteButton').val(resultId);
        });
    </script>
{% endblock %}

ordersorter/templates/ordersorter/test.html
{% extends "myprojects/layout.html"%}

{% load static %}
{% block body %}

<div> Testing out if this loads</div>
  
{% endblock %}